FROM node:18-slim as base

WORKDIR /home/node

EXPOSE 1337

# Chromium dependencies
RUN apt-get update && apt-get install -y \
  gconf-service \
  libgbm-dev \
  libasound2 \
  libatk1.0-0 \
  libc6 \
  libcairo2 \
  libcups2 \
  libdbus-1-3 \
  libexpat1 \
  libfontconfig1 \
  libgcc1 \
  libgconf-2-4 \
  libgdk-pixbuf2.0-0 \
  libglib2.0-0 \
  libgtk-3-0 \
  libnspr4 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libstdc++6 \
  libx11-6 \
  libx11-xcb1 \
  libxcb1 \
  libxcomposite1 \
  libxcursor1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxi6 \
  libxrandr2 \
  libxrender1 \
  libxss1 \
  libxtst6 \
  ca-certificates \
  fonts-liberation \
  libappindicator1 \
  libnss3 \
  lsb-release \
  xdg-utils \
  wget


COPY . .

###########
### DEV ###
###########

FROM base as dev

RUN yarn --immutable --prefer-offline

CMD [ "yarn", "develop" ]

#############
### CLOUD ###
#############

FROM base as cloud

RUN yarn build:nettu

RUN yarn --immutable --prefer-offline --production

RUN yarn build

CMD [ "bash", "-c", "yarn cs:import -y && yarn start" ]