version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - 1337:1337
      - 9229:9229
    volumes:
      - ./:/home/node

  postgres:
    image: pgvector/pgvector:pg13
    ports:
      - "5431:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strapi
volumes:
  postgresdata: